<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ngy_w-30px h-30px border-gray_1 bg-gray_1 hoverborder-gray_2 hoverbg-gray_2 rounded-full flex items-center justify-center p-1 cursor-pointer shadow-md</name>
   <tag></tag>
   <elementGuidId>3c3b1328-7aeb-40e0-92c9-3b24f13decf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div[2]/div[2]/div[2]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6d9a265e-9bf3-495d-a57a-4ca61f04978b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[30px] h-[30px] border-gray_1 bg-gray_1 hover:border-gray_2 hover:bg-gray_2 rounded-full flex items-center justify-center p-1 cursor-pointer shadow-md</value>
      <webElementGuid>87aad304-1cc8-4a73-98f0-d0479d1e9a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen w-full my-0 mx-auto relative main-body&quot;]/main[@class=&quot;mx-auto pt-[65px]&quot;]/div[@class=&quot;flex mt-20&quot;]/div[@class=&quot;w-[70%] min-h-[500px] bg-white rounded-lg flex justify-between&quot;]/div[@class=&quot;w-3/4 p-4 h-full&quot;]/div[@class=&quot;py-4 border-b&quot;]/div[@class=&quot;flex justify-between items-center&quot;]/div[@class=&quot;w-[30px] h-[30px] border-gray_1 bg-gray_1 hover:border-gray_2 hover:bg-gray_2 rounded-full flex items-center justify-center p-1 cursor-pointer shadow-md&quot;]</value>
      <webElementGuid>27078ed8-89ac-481f-ab95-b6cb27a24096</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>0a947400-19ae-4885-8ead-aa9fb600d234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ngày'])[1]/following::div[1]</value>
      <webElementGuid>1594f63a-960e-4bd2-aee1-0d9bce00e053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông tin cá nhân'])[1]/following::div[7]</value>
      <webElementGuid>dbbaee1e-a4f9-46ab-bc6c-ee63291e8cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Công việc'])[1]/preceding::div[1]</value>
      <webElementGuid>7ba1a15f-8d59-4460-a3ed-2d3c739d094d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Học vấn'])[1]/preceding::div[5]</value>
      <webElementGuid>794e9b80-4dec-45e2-9dca-efe71c91f889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>5f20f874-fa03-44ac-ae6f-e0dc3012e246</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
