<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thng tin c nhn84 367673068phunglygmail.comNngy 16 thng 2 nm 2001</name>
   <tag></tag>
   <elementGuidId>2680a3ad-b9f3-403c-91aa-59bb5e3bcb17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.py-4.border-b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div[2]/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d4f7da9d-1c54-4504-8a52-30625bd1c12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-4 border-b</value>
      <webElementGuid>90bd68ef-1add-4123-bf5d-b7eb8b04e8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thông tin cá nhân+84 367673068phungly@gmail.comNữngày 16 tháng 2 năm 2001</value>
      <webElementGuid>bf863fc9-a0b4-4ff7-9394-182517a556f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen w-full my-0 mx-auto relative main-body&quot;]/main[@class=&quot;mx-auto pt-[65px]&quot;]/div[@class=&quot;flex mt-20&quot;]/div[@class=&quot;w-[70%] min-h-[500px] bg-white rounded-lg flex justify-between&quot;]/div[@class=&quot;w-3/4 p-4 h-full&quot;]/div[@class=&quot;py-4 border-b&quot;]</value>
      <webElementGuid>81267c87-0ae4-4087-b2e9-1c8eb8d1d1c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>71d881ed-a447-44e8-863f-d70205318c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phùng Lý'])[3]/following::div[2]</value>
      <webElementGuid>c2f63213-d4fb-4549-85b7-b27d5a9ef48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bạn bè'])[1]/following::div[7]</value>
      <webElementGuid>4a07e627-15a0-441e-acd8-c848195d8212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div</value>
      <webElementGuid>5fa7ea37-39ff-4b2c-95ad-7305e079f797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Thông tin cá nhân+84 367673068phungly@gmail.comNữngày 16 tháng 2 năm 2001' or . = 'Thông tin cá nhân+84 367673068phungly@gmail.comNữngày 16 tháng 2 năm 2001')]</value>
      <webElementGuid>37734f44-c277-44d9-997e-a84f2e00de0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
