<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bn b</name>
   <tag></tag>
   <elementGuidId>b7842051-3443-472b-8a18-81e0e72f0565</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div[2]/div[3]/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c940fba-7ad5-4573-ac1d-f686beca7496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:text-[#fff] text-yellow-50</value>
      <webElementGuid>614a9a4d-219f-489f-98ee-3e97c2ed9b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/profile/643256b0a18074eb1c224622/friends</value>
      <webElementGuid>b10d44c7-4660-4074-abed-ceb468e22375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bạn bè</value>
      <webElementGuid>d8c2468d-e84f-4319-8255-99614c82b195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen w-full my-0 mx-auto relative main-body&quot;]/main[@class=&quot;mx-auto pt-[65px]&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;relative w-[80%] h-[380px]&quot;]/div[@class=&quot;h-[60px] rounded-b-lg w-full z-10 profile-menu&quot;]/ul[@class=&quot;w-[65%] h-full flex items-center justify-items-start uppercase text-[18px]&quot;]/li[@class=&quot;cursor-pointer h-full px-4 flex items-center transition-all border-b-[3px] justify-center font-semibold hover:border-[#fff] hover:transition-all border-transparent&quot;]/a[@class=&quot;hover:text-[#fff] text-yellow-50&quot;]</value>
      <webElementGuid>6aae1b2d-2707-4118-ab65-7be86910285d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div[3]/ul/li[4]/a</value>
      <webElementGuid>7c4f9d05-6349-4313-ad9a-d33df524bbdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bạn bè')]</value>
      <webElementGuid>1d5f90f8-c8da-44ee-b281-b5db95567b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ảnh'])[1]/following::a[1]</value>
      <webElementGuid>cba408b6-b5e0-4450-b014-54ffe6f0e848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giới thiệu'])[1]/following::a[2]</value>
      <webElementGuid>001fdcc1-2c78-4f84-86ca-f140523ad4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giới thiệu'])[2]/preceding::a[1]</value>
      <webElementGuid>afbb90cb-d449-47f7-ab92-b610c7754eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chỉnh sửa'])[1]/preceding::a[1]</value>
      <webElementGuid>53811b40-09b6-4a0a-99c7-b9efebfb16b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bạn bè']/parent::*</value>
      <webElementGuid>7baead1e-7eed-45f1-af1a-a0a529e91116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/profile/643256b0a18074eb1c224622/friends')]</value>
      <webElementGuid>9eba60f8-a82f-4be3-82d1-b70373bc3f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>5b18f549-03e7-42da-ad72-421475b93833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/profile/643256b0a18074eb1c224622/friends' and (text() = 'Bạn bè' or . = 'Bạn bè')]</value>
      <webElementGuid>285b2fb8-d3dd-44c4-a379-e9f3cc09ae62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
