<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Chia s cm ngh ca bn</name>
   <tag></tag>
   <elementGuidId>b8e44f86-3d59-4a54-81ca-c5d4da043e36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div[2]/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>14cbe9e4-3a25-45a6-ac70-40b158caf575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex px-3 justify-around text-white items-center h-[80px] bg-white shadow-sm rounded-lg mb-5</value>
      <webElementGuid>6436f5e6-4c1e-435a-86ba-2be93ed4711f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chia sẻ cảm nghĩ của bạn</value>
      <webElementGuid>5bb2917d-d9ad-4f16-be81-644f7a97be2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen w-full my-0 mx-auto relative main-body&quot;]/main[@class=&quot;mx-auto pt-[65px]&quot;]/div[@class=&quot;flex mt-20&quot;]/div[@class=&quot;w-[70%] min-h-screen flex justify-between&quot;]/div[@class=&quot;w-[59%] rounded-lg h-full flex flex-col&quot;]/div[@class=&quot;flex px-3 justify-around text-white items-center h-[80px] bg-white shadow-sm rounded-lg mb-5&quot;]</value>
      <webElementGuid>cb2cd805-aaf5-48c5-8709-711a9412df22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>2fe92791-98d0-4964-9de1-153a45b971bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bạn bè'])[2]/following::div[2]</value>
      <webElementGuid>320633e3-9c92-418a-9b78-a43ad5bda438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ảnh'])[2]/following::div[5]</value>
      <webElementGuid>4efe2fe8-1f79-4ecd-9e1e-a0b154707dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phùng Lý'])[3]/preceding::div[3]</value>
      <webElementGuid>65977c26-69ce-4ce4-854b-94261f935440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div</value>
      <webElementGuid>fc618517-72fa-4aec-9efc-a92084b2d573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Chia sẻ cảm nghĩ của bạn' or . = 'Chia sẻ cảm nghĩ của bạn')]</value>
      <webElementGuid>cbf89668-6d8a-40ad-8871-e5575d80b103</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
