<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_nh</name>
   <tag></tag>
   <elementGuidId>9ca3f3da-0e6b-4927-a4b7-ed6ac774d4ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.w-full.bg-white.rounded-lg.px-3.pt-4.pb-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>87d77dcd-ffb3-413d-8a5d-02e02a8ec649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full bg-white rounded-lg px-3 pt-4 pb-1</value>
      <webElementGuid>dffa0622-3082-4233-8c17-3953d66475d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ảnh</value>
      <webElementGuid>5cb3a4d7-3fc3-40f7-bd4a-527b306ebdf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen w-full my-0 mx-auto relative main-body&quot;]/main[@class=&quot;mx-auto pt-[65px]&quot;]/div[@class=&quot;flex mt-20&quot;]/div[@class=&quot;w-[70%] min-h-screen flex justify-between&quot;]/div[@class=&quot;w-[39%] h-full&quot;]/div[@class=&quot;mt-5&quot;]/div[@class=&quot;w-full bg-white rounded-lg px-3 pt-4 pb-1&quot;]</value>
      <webElementGuid>9776f411-46d5-4590-8515-b21aa8fe8127</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>7ee21e72-3ac1-46ba-99a0-26e4aa24958a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chỉnh sửa'])[1]/following::div[7]</value>
      <webElementGuid>eeab6758-7ba8-411f-90c3-43836dd948b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giới thiệu'])[2]/following::div[7]</value>
      <webElementGuid>de9bc084-c2c2-4140-bb61-562bf8a18660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bạn bè'])[2]/preceding::div[3]</value>
      <webElementGuid>c57d3d1e-cc6b-4f19-9c11-6d884aa11703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>2da0213b-15f1-4741-8936-7f71ca1620d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ảnh' or . = 'Ảnh')]</value>
      <webElementGuid>4fa8dc15-8640-44a4-be74-21da3ab392b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
