<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>fdefa128-2a5d-4ec4-b507-9e0d48d914d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ant-avatar.ant-avatar-square.ant-avatar-image > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>91209d06-7c51-49c0-8054-ccde17c27d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://res.cloudinary.com/huutx/image/upload/w_350,c_scale/v1681020643/s7jo6tfcmz7xmmclglyw.gif</value>
      <webElementGuid>1ab7f1ba-bc51-4cc1-b0e5-0ae7e090e32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen w-full my-0 mx-auto relative main-body&quot;]/main[@class=&quot;mx-auto pt-[65px]&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;relative w-[80%] h-[380px]&quot;]/div[@class=&quot;absolute w-[150px] h-[150px] bottom-[-22px] left-[28px] rounded-sm avatar-block border-[4px] border-[#fff]&quot;]/span[@class=&quot;ant-avatar ant-avatar-square ant-avatar-image&quot;]/img[1]</value>
      <webElementGuid>355c8f48-6e11-48f6-9090-6566a6194569</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div/span/img</value>
      <webElementGuid>8ea06c77-bab5-42b5-a4a9-8230e3824750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://res.cloudinary.com/huutx/image/upload/w_350,c_scale/v1681020643/s7jo6tfcmz7xmmclglyw.gif')])[2]</value>
      <webElementGuid>2b8d238d-7f9c-46c3-9fa4-80b75c8cea5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/img</value>
      <webElementGuid>d3c69a44-02a4-472a-87d7-08eb3664c607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/huutx/image/upload/w_350,c_scale/v1681020643/s7jo6tfcmz7xmmclglyw.gif']</value>
      <webElementGuid>42ff6778-0e09-4b9e-b7b6-86b363e5a779</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
