<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thng tin c nhn84 367673068phunglygmail._74bf1f</name>
   <tag></tag>
   <elementGuidId>5cc0f92f-531b-4556-825c-77aed2382e3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.py-4.border-b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div[2]/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37009cd4-4e80-4e61-800c-a53e41f2dbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-4 border-b</value>
      <webElementGuid>b36b4f0b-3b19-48fc-ba5e-5ffad08d09e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thông tin cá nhân+84 367673068phungly@gmail.comNữngày 16 tháng 2 năm 2001</value>
      <webElementGuid>dd2a43b2-4df1-4b29-89d9-d4229b663776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen w-full my-0 mx-auto relative main-body&quot;]/main[@class=&quot;mx-auto pt-[65px]&quot;]/div[@class=&quot;flex mt-20&quot;]/div[@class=&quot;w-[70%] min-h-[500px] bg-white rounded-lg flex justify-between&quot;]/div[@class=&quot;w-3/4 p-4 h-full&quot;]/div[@class=&quot;py-4 border-b&quot;]</value>
      <webElementGuid>fa70396c-499c-4047-b91b-00ad7c1cb48c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>984e56e1-5026-4594-ae29-c838f6aed8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phùng Lý'])[3]/following::div[2]</value>
      <webElementGuid>7b115d62-202c-44f5-b930-099d147e025a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bạn bè'])[1]/following::div[7]</value>
      <webElementGuid>d92f5654-fb0c-4377-ac1d-bec76bb5086f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div</value>
      <webElementGuid>17a047b5-6f1e-48ff-989a-cfa14d473e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Thông tin cá nhân+84 367673068phungly@gmail.comNữngày 16 tháng 2 năm 2001' or . = 'Thông tin cá nhân+84 367673068phungly@gmail.comNữngày 16 tháng 2 năm 2001')]</value>
      <webElementGuid>42d54885-e66a-42da-80cd-a949bf595af6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
