<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_a im</name>
   <tag></tag>
   <elementGuidId>768f3b50-5168-468c-921e-c7b04a96545c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/main/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8524144b-4469-41c8-bc76-f7b1cacfdc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-2 py-3 border rounded-2xl shadow-sm min-h-[300px] bg-white</value>
      <webElementGuid>69d08647-91cd-42ea-b04c-398fb8b522a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Địa điểm</value>
      <webElementGuid>2f6b3cfd-735f-4546-ab56-1cc2c4204a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen w-full my-0 mx-auto relative main-body&quot;]/div[@class=&quot;flex border-t-[0.5px] pt-[65px] justify-center&quot;]/main[@class=&quot;w-1/2 static&quot;]/div[@class=&quot;p-3&quot;]/div[@class=&quot;w-full px-2 py-3 border rounded-2xl shadow-sm min-h-[300px] bg-white&quot;]</value>
      <webElementGuid>3d85104a-2d3c-407c-9c83-ed6dc88bf68d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div[2]/div</value>
      <webElementGuid>61abb69a-912b-472b-acef-58fce77ac563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mọi người'])[1]/following::div[2]</value>
      <webElementGuid>75261c52-6946-4fdb-810f-e32b677b52c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bài viết'])[1]/following::div[2]</value>
      <webElementGuid>2efe6c23-f66a-40dd-9639-f3d3d424bc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bài viết'])[2]/preceding::div[1]</value>
      <webElementGuid>d7235472-aaaf-4e29-97ab-3ab334e692fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]/div</value>
      <webElementGuid>2a2484be-ba3f-4487-b679-f7deedd1224c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Địa điểm' or . = 'Địa điểm')]</value>
      <webElementGuid>4e7c364c-7022-46ff-9dbf-132436a9d19a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
