<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ng kPhoneGii tnh Nam  N  Khc Ngy sinhng kBn  c ti khonQuay li trang ng nhp</name>
   <tag></tag>
   <elementGuidId>3bdf6458-6880-4f8a-a7c5-163460c912cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1a9570af-00c3-4ef9-95e5-e2812267ac42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[450px] mt-20</value>
      <webElementGuid>2a6624c5-3e48-4ab0-98dc-d4dd5cc172e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng kýPhoneGiới tính Nam  Nữ  Khác Ngày sinhĐăng kýBạn đã có tài khoản?Quay lại trang đăng nhập</value>
      <webElementGuid>946ee26a-7f31-43fa-b066-f220bec2ea86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen w-full my-0 mx-auto relative core-body&quot;]/main[@class=&quot;mx-auto&quot;]/div[@class=&quot;flex relative&quot;]/div[@class=&quot;w-1/2 bg-transparent flex justify-center absolute right-0&quot;]/div[@class=&quot;w-[450px] mt-20&quot;]</value>
      <webElementGuid>73c2e61d-1538-41da-a49c-7af538f4f6b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div</value>
      <webElementGuid>468a53d5-642e-4540-9c58-9b63f7a9b3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>1b9bfa5d-014e-4b98-89a6-daf956ab43b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Đăng kýPhoneGiới tính Nam  Nữ  Khác Ngày sinhĐăng kýBạn đã có tài khoản?Quay lại trang đăng nhập' or . = 'Đăng kýPhoneGiới tính Nam  Nữ  Khác Ngày sinhĐăng kýBạn đã có tài khoản?Quay lại trang đăng nhập')]</value>
      <webElementGuid>eda98f0b-bd37-425b-8522-e715e6301381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
