<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_ng kPhoneGii tnh Nam  N  Khc Ngy sinhng k</name>
   <tag></tag>
   <elementGuidId>19b66dd1-e003-4b0d-8ab6-4f15c075d217</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.ant-form.ant-form-horizontal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div[2]/div/form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>1988c6e7-3c3d-4b8d-af91-9336c76c81ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-form ant-form-horizontal</value>
      <webElementGuid>4c4a94ae-1965-4513-9f91-22aac2c0e64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng kýPhoneGiới tính Nam  Nữ  Khác Ngày sinhĐăng ký</value>
      <webElementGuid>ec4ff1ca-0249-4ded-9475-70be3a51b518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen w-full my-0 mx-auto relative core-body&quot;]/main[@class=&quot;mx-auto&quot;]/div[@class=&quot;flex relative&quot;]/div[@class=&quot;w-1/2 bg-transparent flex justify-center absolute right-0&quot;]/div[@class=&quot;w-[450px] mt-20&quot;]/form[@class=&quot;ant-form ant-form-horizontal&quot;]</value>
      <webElementGuid>42d4befe-087e-43a7-a58c-5231f1823fc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div/form</value>
      <webElementGuid>f142cf45-d218-4859-b064-cf4ff7113049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>4d759ff0-dcfb-44d1-b19d-8c9c497e21d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'Đăng kýPhoneGiới tính Nam  Nữ  Khác Ngày sinhĐăng ký' or . = 'Đăng kýPhoneGiới tính Nam  Nữ  Khác Ngày sinhĐăng ký')]</value>
      <webElementGuid>4234b108-80e9-409f-9fa7-18ff57214961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
