<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>b903fb11-0226-4699-bdba-1184fcead7e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/button/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>01ba436a-a426-4aad-9840-ae75bf6a7a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://res.cloudinary.com/huutx/image/upload/w_350,c_scale/v1681020643/s7jo6tfcmz7xmmclglyw.gif</value>
      <webElementGuid>453da0da-d10b-4caf-8425-526046a756cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen w-full my-0 mx-auto relative main-body&quot;]/div[@class=&quot;flex h-[65px] w-full justify-between bg-white items-center px-10 fixed z-50&quot;]/div[@class=&quot;flex items-center mt-1&quot;]/button[@class=&quot;ant-dropdown-trigger&quot;]/span[@class=&quot;ant-avatar ant-avatar-circle ant-avatar-image border-[0.5px] border-[#dadada]&quot;]/img[1]</value>
      <webElementGuid>6e7d6410-8a22-4990-8f87-a4e890b143f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/button/span/img</value>
      <webElementGuid>d5d43ec2-841c-4b02-9e84-af789d6f7c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://res.cloudinary.com/huutx/image/upload/w_350,c_scale/v1681020643/s7jo6tfcmz7xmmclglyw.gif')]</value>
      <webElementGuid>f31f48ef-3d49-417e-a351-5219f96b0361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>ddcee223-f72b-487e-8d28-4d9565be4faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/huutx/image/upload/w_350,c_scale/v1681020643/s7jo6tfcmz7xmmclglyw.gif']</value>
      <webElementGuid>5770126e-fdba-4141-8bb1-49737d93619d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
