<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ngy_work</name>
   <tag></tag>
   <elementGuidId>2143cf8d-cb10-407e-a629-c6305abab305</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#work</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='work']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>682473d3-d8c1-4031-9a97-e764a35c4def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e31495b5-387c-491e-9810-8b7e124854ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Đã làm việc</value>
      <webElementGuid>a16490ba-9bdf-4144-ba51-8b34bdafc587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>work</value>
      <webElementGuid>0cf16c97-f9b7-4204-a362-9e122c6707d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg rounded-md w-full text-[14px]</value>
      <webElementGuid>3bd890b0-c1e8-4761-9899-ccb35009b109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;work&quot;)</value>
      <webElementGuid>f9f4975c-d5ba-4889-aca6-db6e4296004f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='work']</value>
      <webElementGuid>8aa73c0b-d424-47c5-8dec-dfbf328076c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div[2]/div[2]/div[2]/form/div[3]/div/div/div/div/input</value>
      <webElementGuid>cddd6fd3-0a0f-46f2-aec2-2c28fac63e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>e59e9643-9d52-403b-a8bf-67d7913326e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Đã làm việc' and @id = 'work']</value>
      <webElementGuid>1e1cef31-3f44-4e27-a9a9-0fa719429196</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
