<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_ng kPhoneGii tnh Nam  N  Khc Ngy sinhng k</name>
   <tag></tag>
   <elementGuidId>35c9d6be-7cde-497c-ac7c-cc11c0328a64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.ant-form.ant-form-horizontal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div[2]/div/form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>11d5dfce-4ac7-4859-9731-8af2a25c15e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-form ant-form-horizontal</value>
      <webElementGuid>000f1030-9863-4244-903f-a1fb28d00a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng kýPhoneGiới tính Nam  Nữ  Khác Ngày sinhĐăng ký</value>
      <webElementGuid>89bdc962-9963-4949-94a1-060ee75f62ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen w-full my-0 mx-auto relative core-body&quot;]/main[@class=&quot;mx-auto&quot;]/div[@class=&quot;flex relative&quot;]/div[@class=&quot;w-1/2 bg-transparent flex justify-center absolute right-0&quot;]/div[@class=&quot;w-[450px] mt-20&quot;]/form[@class=&quot;ant-form ant-form-horizontal&quot;]</value>
      <webElementGuid>0bd4983a-dbcf-403b-86e3-2d99a4ee9859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div/form</value>
      <webElementGuid>71af2fb5-d612-4b8e-9718-7a51ff182286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>f84d2316-b37b-40c9-a4d3-afa9dcc12e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'Đăng kýPhoneGiới tính Nam  Nữ  Khác Ngày sinhĐăng ký' or . = 'Đăng kýPhoneGiới tính Nam  Nữ  Khác Ngày sinhĐăng ký')]</value>
      <webElementGuid>ad842ae3-7d40-465e-8533-d3aa23073dc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
