<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Phng L_w-36px h-36px border-0.5px border-8B239C rounded-full mr-3 cursor-pointer flex items-center justify-center bg-8B239C hoverbg-761b84 hoverborder-761b84</name>
   <tag></tag>
   <elementGuidId>7d0d617f-1bc3-490c-b8a5-d9ad080e5eac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>29cf0f8d-677a-4e97-aa99-dddc782fd1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[36px] h-[36px] border-[0.5px] border-[#8B239C] rounded-full mr-3 cursor-pointer flex items-center justify-center bg-[#8B239C] hover:bg-[#761b84] hover:border-[#761b84]</value>
      <webElementGuid>2afb3e2a-5079-426c-81c4-37c0624d74bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen w-full my-0 mx-auto relative main-body&quot;]/div[@class=&quot;flex h-[65px] w-full justify-between bg-white items-center px-10 fixed z-50&quot;]/div[@class=&quot;flex items-center mt-1&quot;]/div[@class=&quot;w-[36px] h-[36px] border-[0.5px] border-[#8B239C] rounded-full mr-3 cursor-pointer flex items-center justify-center bg-[#8B239C] hover:bg-[#761b84] hover:border-[#761b84]&quot;]</value>
      <webElementGuid>e50cda7e-b78b-46c2-b3c6-94b148d0ff9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div</value>
      <webElementGuid>f0464dba-849e-4d2f-a830-aac6ca8f71f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phùng Lý'])[1]/preceding::div[1]</value>
      <webElementGuid>b09ac0fd-d491-4779-840c-ab0d88e83cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phùng Lý'])[2]/preceding::div[2]</value>
      <webElementGuid>edf17a37-1b41-4d0f-8e65-f11d31761753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div</value>
      <webElementGuid>5e028bd2-015f-4827-8a97-4da9de41364e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
