<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Phng L_ant-image-img</name>
   <tag></tag>
   <elementGuidId>60286bc8-7914-485d-84d5-1c3db0b817ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.ant-image-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b6d8af41-d9cc-4db5-b368-136910d11ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo</value>
      <webElementGuid>2c875c80-3839-4d7f-a6b0-8fc0786c6a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-image-img</value>
      <webElementGuid>6cc4e769-64b4-42c0-8848-583473ff9f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/logo.webp</value>
      <webElementGuid>ae734db3-7c33-4023-88b3-c066f5944d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>64397abe-9fba-4af4-be0d-de763d8b1c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-h-screen w-full my-0 mx-auto relative main-body&quot;]/div[@class=&quot;flex h-[65px] w-full justify-between bg-white items-center px-10 fixed z-50&quot;]/div[@class=&quot;inline-flex items-center&quot;]/div[@class=&quot;h-auto cursor-pointer mr-2&quot;]/a[@class=&quot;flex items-center&quot;]/div[@class=&quot;ant-image&quot;]/img[@class=&quot;ant-image-img&quot;]</value>
      <webElementGuid>d6a71c5b-cefa-44c8-a05b-25931add46a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/a/div/img</value>
      <webElementGuid>41c107ce-e773-4b81-a5ea-bb24c6088987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo']</value>
      <webElementGuid>e4831d58-fa04-41e5-a653-bb38347d72d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>e9b80633-a099-455a-8b97-46399109a032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Logo' and @src = '/images/logo.webp']</value>
      <webElementGuid>e4f366b4-0c86-4eb0-b236-e8d013840751</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
